 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
211.179.124.141 - - [17/Nov/2017 16:17:52] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:17:52] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:17:53] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:18:00] "GET / HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:18:31] "POST /message HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:18:31] "GET /keyboard HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:18:31] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:18:34] "GET /mpas HTTP/1.1" 404 -
211.179.124.141 - - [17/Nov/2017 16:18:39] "GET /maps HTTP/1.1" 302 -
211.179.124.141 - - [17/Nov/2017 16:18:39] "GET /fail HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
211.179.124.141 - - [17/Nov/2017 16:23:46] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:23:47] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:23:49] "GET /fail HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:23:50] "GET /fail HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
211.179.124.141 - - [17/Nov/2017 16:24:33] "GET /fail HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:24:35] "GET /fail HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:24:44] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:24:44] "GET / HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
211.179.124.141 - - [17/Nov/2017 16:25:58] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:25:58] "GET / HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:09] "DELETE /friend/test HTTP/1.1" 404 -
110.76.143.235 - - [17/Nov/2017 16:26:09] "POST /friend HTTP/1.1" 404 -
110.76.143.235 - - [17/Nov/2017 16:26:09] "DELETE /chat_room/test HTTP/1.1" 404 -
110.76.143.235 - - [17/Nov/2017 16:26:09] "GET /keyboard HTTP/1.1" 200 -
211.231.103.91 - - [17/Nov/2017 16:26:10] "GET / HTTP/1.1" 200 -
211.231.103.107 - - [17/Nov/2017 16:26:11] "GET / HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:11] "DELETE /friend/test HTTP/1.1" 404 -
110.76.143.234 - - [17/Nov/2017 16:26:11] "POST /friend HTTP/1.1" 404 -
110.76.143.234 - - [17/Nov/2017 16:26:11] "DELETE /chat_room/test HTTP/1.1" 404 -
110.76.143.234 - - [17/Nov/2017 16:26:11] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:26] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:26:27] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:13] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:27:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [17/Nov/2017 16:27:20] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:24] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:25] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:26] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:26] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:28] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:28] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:32] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:32] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:33] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:33] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:34] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:34] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:34] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:35] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:35] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:35] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:27:36] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:36] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:37] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.236 - - [17/Nov/2017 16:27:41] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.234 - - [17/Nov/2017 16:27:54] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
211.179.124.141 - - [17/Nov/2017 16:28:06] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:28:06] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:28:06] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:28:07] "GET / HTTP/1.1" 200 -
211.179.124.141 - - [17/Nov/2017 16:28:13] "GET /maps HTTP/1.1" 302 -
211.179.124.141 - - [17/Nov/2017 16:28:13] "GET /fail HTTP/1.1" 200 -
110.76.143.235 - - [17/Nov/2017 16:28:15] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:28:18] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:28:23] "DELETE /chat_room/FZJI1w_bwYqE HTTP/1.1" 404 -
110.76.143.235 - - [17/Nov/2017 16:28:28] "POST /message HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kimjaejin/github/python/chatbot/chatbot.py", line 159, in Message
    parse=re.sub('[ ]','',content)
NameError: name 're' is not defined
110.76.143.235 - - [17/Nov/2017 16:28:34] "POST /message HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
175.223.32.29 - - [20/Nov/2017 07:41:51] "GET / HTTP/1.1" 200 -
175.223.32.29 - - [20/Nov/2017 07:41:52] "GET /favicon.ico HTTP/1.1" 404 -
175.223.32.29 - - [20/Nov/2017 07:41:53] "GET / HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:42:30] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:42:30] "DELETE /chat_room/FZJI1w_bwYqE HTTP/1.1" 404 -
175.223.32.29 - - [20/Nov/2017 07:42:30] "GET / HTTP/1.1" 200 -
175.223.32.29 - - [20/Nov/2017 07:42:32] "GET / HTTP/1.1" 200 -
175.223.32.29 - - [20/Nov/2017 07:44:19] "GET /favicon.ico HTTP/1.1" 404 -
110.76.143.235 - - [20/Nov/2017 07:45:41] "DELETE /friend/test HTTP/1.1" 404 -
110.76.143.235 - - [20/Nov/2017 07:45:41] "POST /friend HTTP/1.1" 404 -
110.76.143.235 - - [20/Nov/2017 07:45:41] "DELETE /chat_room/test HTTP/1.1" 404 -
110.76.143.235 - - [20/Nov/2017 07:45:41] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:46] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:45:57] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:46:15] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 07:47:57] "GET /keyboard HTTP/1.1" 200 -
175.223.32.29 - - [20/Nov/2017 07:48:22] "GET / HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 07:51:20] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:51:23] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:51:32] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 07:51:41] "POST /message HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 08:45:52] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 08:45:53] "POST /message HTTP/1.1" 200 -
66.102.6.102 - - [20/Nov/2017 09:05:06] "GET /maps HTTP/1.1" 302 -
66.102.6.104 - - [20/Nov/2017 09:05:07] "GET /fail HTTP/1.1" 200 -
66.102.6.102 - - [20/Nov/2017 09:05:07] "GET /favicon.ico HTTP/1.1" 404 -
110.76.143.236 - - [20/Nov/2017 09:07:58] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:08:00] "POST /message HTTP/1.1" 200 -
66.102.6.99 - - [20/Nov/2017 09:09:30] "GET / HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 09:22:38] "GET /keyboard HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 09:22:38] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:22:42] "POST /message HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 09:23:45] "POST /message HTTP/1.1" 200 -
211.231.103.91 - - [20/Nov/2017 09:23:45] "GET /maps HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:23:52] "GET /maps HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:23:52] "GET /ajax HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:23:54] "GET /favicon.ico HTTP/1.1" 404 -
110.76.143.236 - - [20/Nov/2017 09:26:16] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:26:20] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 09:26:26] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 09:30:00] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 09:30:14] "POST /message HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:30:17] "GET /maps HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:30:18] "GET /ajax HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:30:20] "GET /favicon.ico HTTP/1.1" 404 -
110.76.143.234 - - [20/Nov/2017 09:34:22] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:34:28] "POST /message HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:34:30] "GET /maps HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:34:31] "GET /ajax HTTP/1.1" 200 -
211.179.124.141 - - [20/Nov/2017 09:34:32] "GET /favicon.ico HTTP/1.1" 404 -
110.76.143.234 - - [20/Nov/2017 09:42:02] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:42:04] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 09:42:07] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.235 - - [20/Nov/2017 10:06:03] "GET /keyboard HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 10:06:04] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:06:10] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 10:06:15] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:06:18] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 10:06:21] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:06:24] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.236 - - [20/Nov/2017 10:07:03] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:07:06] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.236 - - [20/Nov/2017 10:09:56] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:10:04] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.234 - - [20/Nov/2017 10:46:58] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 10:46:59] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 10:47:02] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.236 - - [20/Nov/2017 11:25:42] "GET /keyboard HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:25:43] "POST /message HTTP/1.1" 200 -
110.76.143.234 - - [20/Nov/2017 11:25:46] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:26:02] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 11:26:04] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:26:10] "POST /message HTTP/1.1" 200 -
 * Detected change in '/home/kimjaejin/github/python/chatbot/chatbot.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 131-718-151
110.76.143.234 - - [20/Nov/2017 11:27:50] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:27:52] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:27:55] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 11:28:01] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:28:05] "POST /message HTTP/1.1" 200 -
110.76.143.235 - - [20/Nov/2017 11:28:10] "POST /message HTTP/1.1" 200 -
110.76.143.236 - - [20/Nov/2017 11:28:13] "POST /message HTTP/1.1" 200 -
